org: pickgeul
app: pickgeul-server
service: pickgeul-server-prod

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-webpack
  - serverless-webpack-prisma

custom:
  customDomain:
    domainName: ${param:DOMAIN}
    certificateName: '*.your_domain.com'
    basePath: ''
    createRoute53Record: true
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'yarn'
#   enterprise:
#     collectLambdaLogs: false
#     disableAwsSpans: true
#     disableHttpSpans: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  # remember that serverless.com supports Japan only for now
  region: ap-northeast-1
  timeout: 15
  environment:
    DATABASE_URL: ${param:DATABASE_URL}
    DATABASE_NAME: ${param:DATABASE_NAME}

    EMAIL_SERVICE: ${param:EMAIL_SERVICE}
    EMAIL_HOST: ${param:EMAIL_HOST}
    EMAIL_PORT: ${param:EMAIL_PORT}
    # This repository assumes you are using gmail for sending emails
    EMAIL_AUTH_USER: ${param:EMAIL_AUTH_USER}
    EMAIL_AUTH_PASSWORD: ${param:EMAIL_AUTH_PASSWORD}

    CLIENT_URL: ${param:CLIENT_URL}

    JWT_ACCESS_TOKEN_SECRET: ${param:JWT_ACCESS_TOKEN_SECRET}
    JWT_ACCESS_TOKEN_EXPIRATION_TIME: ${param:JWT_ACCESS_TOKEN_EXPIRATION_TIME}
    JWT_REFRESH_TOKEN_SECRET: ${param:JWT_REFRESH_TOKEN_SECRET}
    JWT_REFRESH_TOKEN_EXPIRATION_TIME: ${param:JWT_REFRESH_TOKEN_EXPIRATION_TIME}

  vpc:
    securityGroupIds:
      - ${param:SECURITY_GROUP_ID}
    subnetIds:
      - ${param:PRIVATE_SUBNET_1}
      - ${param:PRIVATE_SUBNET_2}

  logRetentionInDays: 7 # Set the default RetentionInDays for a CloudWatch LogGroup
  logs:
    restApi: # Optional configuration which specifies if API Gateway logs are used. This can either be set to `true` to use defaults, or configured via subproperties. Can only be configured if API Gateway is inside a stack.
      accessLogging: true # Optional configuration which enables or disables access logging. Defaults to true.
      executionLogging: true # Optional configuration which enables or disables execution logging. Defaults to true.
      level: ERROR # Optional configuration which specifies the log level to use for execution logging. May be set to either INFO or ERROR.
      fullExecutionData: true # Optional configuration which specifies whether or not to log full requests/responses for execution logging. Defaults to true.
package:
  individually: true

functions:
  main: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    timeout: 30
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
          cors: true
